version: '2'
services:  
  load-balancer:
    ports:
    - ${HOST_PORT}
    image: rancher/lb-service-haproxy:v0.5.9
    labels:
      proxy_url: ${EXPOSE_URL}
      io.rancher.container.network: true
  web:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.network: true
    image: krack/yoga-site:${TAG}